apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zh9m5sjjd-python
  janus-idp.io/tekton: zh9m5sjjd-python
  backstage.io/kubernetes-id: zh9m5sjjd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zh9m5sjjd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
