apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zh9m5sjjd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zh9m5sjjd-python 
  name: zh9m5sjjd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zh9m5sjjd-python 
